-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')

-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.nullls')
require('plugins.autopairs')
require('plugins.tsautotag')
require('plugins.bufferline')
require('plugins.outline')
require('plugins.lualine')
require('plugins.gitsigns')
require('plugins.comment')
require('plugins.lazygit')
require('plugins.toggleterm')
require('plugins.neotest')
require('plugins.hop')
require('plugins.lspprogress')
require('plugins.trouble')
require('plugins.todocomments')
require('plugins.project')
